version: '3'
services:
  app:
    container_name: sls-app
    image: sls-app:latest
    build: ./
    volumes:
      - ./lambda_function.py:/opt/app/lambda_function.py
      - ./src:/opt/app/src
    ports:
      - 28080:80
    command: npm run run
