version: '3'
services:
  app:
    container_name: sls-app
    image: sls-app:latest
    build: ./
    volumes:
      - ./package.json:/opt/app/package.json
      - ./serverless.yml:/opt/app/serverless.yml
      - ./lambda_function.py:/opt/app/lambda_function.py
    ports:
      - 28080:80
