service: sls-ws-app

plugins:
  - serverless-offline-python

provider:
  name: aws
  runtime: python3.6

custom:
  serverless-offline:
    port: 80

functions:
  app1:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: /app1/{method}
          method: get

  app2:
    handler: src.lambda_function.lambda_handler
    events:
      - http:
          path: /app2/{method}
          method: get

